<?php
    $_product = $block->getProduct();
?>
<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
<div id="bundleSummary" class="block-bundle-summary block-bundle-customization-functional-boxer">
    <div class="title">
        <strong><?php /* @escapeNotVerified */ echo __('Your Customization'); ?></strong>
    </div>
    <div class="content">
        <div class="bundle-info">
            <?php echo $block->getImage($_product, 'bundled_product_customization_page')->toHtml(); ?>
            <div class="product-details">
                <?php 
                if($_product->getId() == '1145' || $_product->getId() == '1548'){ ?>
                <div class="parent-container-common-show-hide-fixed swatch-attribute size-custom-functional-boxer">
                    <div class="fixed-select-size-box box-select-common">
                        <a href="#">
                            <span class="swatch-attribute-label"><?= __('Size');?></span>
                            <strong class="swatch-attribute-selected-option swatch-attribute-selected-option-custom-functional-boxer-size"></strong>
                        </a>
                    </div>
                    <div class="container-fixed-size-product-view-only container-show-hide-attribute-common fixed-style-type-text-swatch">
                        <div class="swatch-attribute-options clearfix">
                            <div class="swatch-option text fixed-click-size-bundle-customization-functional-boxer" option-label="<?= __('ALL');?>" aria-label="<?= __('ALL');?>" option-tooltip-value="<?= __('ALL');?>"><?= __('ALL');?></div>
                        </div>
                    </div>
                </div>
                <?php 
                }
                ?>
                <strong class="product name"><?php echo $block->escapeHtml($_product->getName()) ?></strong>
                <?php if ($_product->getIsSalable()): ?>
                    <p class="available stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                    </p>
                <?php else: ?>
                    <p class="unavailable stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                    </p>
                <?php endif; ?>
                <?php echo $block->getChildHtml('', true);?>
            </div>
        </div>
        <div class="bundle-summary">
            <strong class="subtitle"><?php /* @escapeNotVerified */ echo __('Summary'); ?></strong>
            <div id="bundle-summary" data-container="product-summary">
                <input type="checkbox" name="summary-changed" id="summary-changed" style="opacity: 0;" />
                <ul data-mage-init='{"productSummary": []}' class="bundle items"></ul>
                <script data-template="bundle-summary" type="text/x-magento-template">
                    <li>
                        <strong class="label"><%- data._label_ %>:</strong>
                        <div data-container="options"></div>
                    </li>
                </script>
                <script data-template="bundle-super" type="text/x-magento-template">
                    <div>
                        <strong>
                            <?php /* @escapeNotVerified */ echo __('%1', '<%- data._label_ %>') ?>
                        </strong> : <?php /* @escapeNotVerified */ echo __('%1', '<%- data._value_ %>') ?>
                    </div>
                </script>
                <script data-template="bundle-custom" type="text/x-magento-template">
                    <div>
                        <strong>
                            <?php /* @escapeNotVerified */ echo __('%1', '<%- data._label_ %>') ?>
                        </strong>
                    </div>
                </script>
                <script data-template="bundle-price" type="text/x-magento-template">
                    <div>
                        <strong>
                            <?php /* @escapeNotVerified */ echo __('Price') ?>
                        </strong> : <span data-amount="<%- data.amount %>" data-role="bundle-summary-price-<?php /* @escapeNotVerified */ echo __('%1', '<%- data._option_id_ %>') ?>">
                            <?php /* @escapeNotVerified */ echo __('%1', '<%- data.price %>') ?>
                        </span>
                    </div>
                </script>
                <script data-template="bundle-option" type="text/x-magento-template">
                    <div>
                        <div class="summary-option-label">
                            <?php /* @escapeNotVerified */ echo __('%1 x %2', '<%- data._quantity_ %>', '<%- data._label_ %>') ?>
                        </div>
                        <div class="summary-option-super" data-container="summary-super"></div>
                        <div class="summary-option-custom" data-container="summary-custom"></div>
                        <div class="summary-option-price" data-container="summary-price"></div>
                    </div>
                </script>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 1500,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".product-add-form"
                <?php if ($block->isStartCustomization()): ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>

<script type="text/x-magento-init">
    {
        ".product-add-form": {
            "Wizkunde_ConfigurableBundle/js/bundle-conditions": {
                "cascade": <?= /* @escapeNotVerified */ $_product->getBundleCascadeQty() ?>
            }
        }
    }
</script>
<?php endif; ?>