<div class="sign-in-out-container forgot-container">
	<div class="container">
		<div class="row">
			<div class="block block-customer-sign-in-out block-customer-forgot">
				<div class="block-title">
					<strong id="block-customer-sign-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Reset Password')) ?></strong>
				</div>
				<div class="block-content" aria-labelledby="block-customer-sign-heading">
					<form class="form password forget"
						action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
						method="post"
						id="form-validate"
						data-mage-init='{"validation":{}}'>
						<fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
							<div class="field note text-center"><?= $block->escapeHtml(__('Don\'t worry, it happens to the best of us.')) ?></div>
							<div class="field note text-center"><?= $block->escapeHtml(__('Enter your email address and we\'ll send you a link to reset your password.')) ?></div>
							<div class="field email">
								<label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?>:</span></label>
								<div class="control">
									<input type="email" name="email" alt="email" id="email_address" class="input-text" placeholder="example@gmail.com" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
								</div>
							</div>
						</fieldset>
                        <div class="actions-toolbar">
                            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Send Email')) ?></span></button>
                        </div>
                        <div class="links-block">
                            <div class="text-center link-sign-in">
                                <?= $block->escapeHtml(__("Return to")) ?>
                                <a href="<?= $block->getUrl('customer/account/login') ?>" class="action"><?= $block->escapeHtml(__('Sign In')) ?></a>
                            </div>
                        </div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

