<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<div class="sign-in-out-container register-container">
	<div class="container">
		<div class="row">
			<div class="block block-customer-sign-in-out block-customer-register">
				<div class="block-title">
					<strong id="block-customer-sign-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Sign Up')) ?></strong>
				</div>
				<div class="block-content" aria-labelledby="block-customer-sign-heading">
					<form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
					<?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
					
					<?php if ($block->getShowAddressFields()) : ?>
						<fieldset class="fieldset address">
							<legend class="legend"><span><?= $block->escapeHtml(__('Address Information')) ?></span></legend><br>
							<input type="hidden" name="create_address" value="1" />

							<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
							<?php if ($_company->isEnabled()) : ?>
								<?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
							<?php endif ?>

							<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
							<?php if ($_telephone->isEnabled()) : ?>
								<?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
							<?php endif ?>

							<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
							<?php if ($_fax->isEnabled()) : ?>
								<?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
							<?php endif ?>
							<?php //phpcs:disable ?>
							<?php $_streetValidationClass = $this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street'); ?>
							<?php //phpcs:enable ?>
							<div class="field street">
								<label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
								<div class="control">
									<input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
									<div class="nested">
										<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
										<?php //phpcs:disable ?>
										<?php for ($_i = 2, $_n = $this->helper(\Magento\Customer\Helper\Address::class)->getStreetLines(); $_i <= $_n; $_i++) : ?>
										<?php //phpcs:enable ?>
											<div class="field additional">
												<label class="label" for="street_<?= /* @noEscape */ $_i ?>">
													<span><?= $block->escapeHtml(__('Address')) ?></span>
												</label>
												<div class="control">
													<input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
												</div>
											</div>
										<?php endfor; ?>
									</div>
								</div>
							</div>

							<div class="field">
								<label for="city" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
								<div class="control">
									<?php //phpcs:disable ?>
									<input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="city">
									<?php //phpcs:enable ?>
								</div>
							</div>

							<div class="field region">
								<label for="region_id" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
								<div class="control">
									<select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select region_id" style="display:none;">
										<option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
									</select>
									<?php //phpcs:disable ?>
									<input type="text" id="region" name="region" value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>" style="display:none;">
									<?php //phpcs:enable ?>
								</div>
							</div>

							<div class="field zip">
								<label for="zip" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
								<div class="control">
									<?php //phpcs:disable ?>
									<input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>">
									<?php //phpcs:enable ?>
								</div>
							</div>

							<div class="field country">
								<label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
								<div class="control">
									<?= $block->getCountryHtmlSelect() ?>
								</div>
							</div>
							<?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
							<?php if ($addressAttributes) : ?>
								<?php $addressAttributes->setEntityType('customer_address'); ?>
								<?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
								<?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
								<?= $addressAttributes->setShowContainer(false)->toHtml() ?>
							<?php endif;?>
							<input type="hidden" name="default_billing" value="1">
							<input type="hidden" name="default_shipping" value="1">
						</fieldset>

					<?php endif; ?>
					<fieldset class="fieldset create info">
						<input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
						<input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">

                        <div class="field email">
                            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?>:</span></label>
                            <div class="control">
                                <input
                                        type="email"
                                        name="email"
                                        autocomplete="email"
                                        id="email_address"
                                        value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                        class="input-text"
                                        placeholder="example@gmail.com"
                                        data-mage-init='{"mage/trim-input":{}}'
                                        data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>

                        <div class="field gender">
                            <label for="gender" class="label"><span><?= $block->escapeHtml(__('Title')) ?>:</span></label>
                            <?php $gender = $block->escapeHtmlAttr($block->getFormData()->getGender());?>
                            <div class="control">
                                <label class="label">
                                    <input type="radio" name="gender" value="1" class="radio" <?php if ($gender === '1' || empty($gender)) : ?>checked="checked"<?php endif; ?>>
                                    <?= __('Mr') ?>
                                </label>
                                <label class="label">
                                    <input type="radio" name="gender" value="2" class="radio" <?php if ($gender === '2') : ?>checked="checked"<?php endif; ?>>
                                    <?= __('Mrs') ?>
                                </label>
                            </div>
                        </div>

                        <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

						<?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
						<?php if ($_dob->isEnabled()) : ?>
                            <div class="field date field-dob">
                                <label class="label" for="dob"><span><?= $block->escapeHtml(__('Date of Birth')) ?>:</span></label>
                                <div class="control customer-dob">
                                    <input
                                            type="text"
                                            name="dob"
                                            id="dob"
                                            value=""
                                            placeholder="MM/DD/YYYY"
                                            data-validate="{'validate-date':{'dateFormat':'DD/MM/YYYY'},'validate-dob-eu':true}"/>
                                </div>
                            </div>
						<?php endif ?>

						<?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
						<?php if ($_taxvat->isEnabled()) : ?>
							<?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
						<?php endif ?>
						
					</fieldset>
					
					<fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
						
						<div class="field password">
							<label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?>:</span></label>
							<div class="control">
								<input type="password" name="password" id="password"
									title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
									class="input-text"
									data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
									data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
									data-validate="{required:true, 'validate-customer-password':true}"
									autocomplete="off">
                                <button type="button" class="show-hide-password-btn">
                                    <i class="fas fa-eye"></i>
                                </button>
								<div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
									<div id="password-strength-meter" class="password-strength-meter">
										<?= $block->escapeHtml(__('Password Strength')) ?>:
										<span id="password-strength-meter-label" data-role="password-strength-meter-label">
											<?= $block->escapeHtml(__('No Password')) ?>
										</span>
									</div>
								</div>
							</div>
						</div>
						<div class="field confirmation">
							<label for="password-confirmation" class="label"><span><?= $block->escapeHtml(__('Confirm Password')) ?>:</span></label>
							<div class="control">
								<input type="password" name="password_confirmation" title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                                <button type="button" class="show-hide-password-btn">
                                    <i class="fas fa-eye"></i>
                                </button>
							</div>
						</div>
					</fieldset>
					<div class="actions-toolbar">
                        <button type="submit" class="action register primary" title="<?= $block->escapeHtmlAttr(__('Sign Up')) ?>"><span><?= $block->escapeHtml(__('Sign Up')) ?></span></button>
					</div>
                    <div class="links-block">
                        <div class="text-center links-terms">
                            <?= $block->escapeHtml(__('By creating an account, you accept')) ?>
                            <a href="<?= $block->getUrl('terms-and-conditions') ?>" class="action"><?= $block->escapeHtml(__('Terms & Conditions')) ?></a>
                            <?= $block->escapeHtml(__('and acknowledge our')) ?>
                            <a href="<?= $block->getUrl('data-protection') ?>" class="action"><?= $block->escapeHtml(__('Data Protection (Privacy)')) ?></a>
                        </div>
                        <div class="text-center link-sign-in">
                            <?= $block->escapeHtml(__('Already have an account? Sign in')) ?>
                            <a href="<?= $block->getUrl('customer/account/login/') ?>" class="action"><?= $block->escapeHtml(__('here')) ?></a>
                        </div>
                    </div>
                    </form>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()) : ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else : ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');
});
</script>
<?php if ($block->getShowAddressFields()) : ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                <?php //phpcs:disable ?>
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                <?php //phpcs:enable ?>
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                <?php //phpcs:disable ?>
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                <?php //phpcs:enable ?>
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Customer/js/validation": {}
    },
    ".field.password": {
        "passwordStrengthIndicator": {
            "formSelector": "form.form-create-account"
        }
    }
}
</script>
