<div class="sign-in-out-container set-password-container">
    <div class="container">
        <div class="row">
            <div class="block block-customer-sign-in-out block-customer-set-password">
                <div class="block-title">
                    <strong id="block-customer-sign-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Reset Password')) ?></strong>
                </div>
                <div class="block-content" aria-labelledby="block-customer-sign-heading">
                    <form class="form account form-set-password"
                          action="<?= $block->escapeUrl($block->getUrl('*/*/resetpasswordpost', ['_query' => ['token' => $block->getResetPasswordLinkToken()]])) ?>"
                          id="form-validate"
                          class="form password reset"
                          data-mage-init='{"validation":{}}'
                          method="post"
                          enctype="multipart/form-data"
                          autocomplete="off">
                        <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>

                        <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                            <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                                <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
                                <div class="control">
                                    <input type="password" class="input-text" name="password" id="password"
                                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                           data-validate="{required:true, 'validate-customer-password':true}"
                                           autocomplete="off">
                                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                        <div id="password-strength-meter" class="password-strength-meter">
                                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                                <?= $block->escapeHtml(__('No Password')) ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="field confirmation required">
                                <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
                                <div class="control">
                                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation" data-validate="{required:true,equalTo:'#password'}" autocomplete="off">
                                </div>
                            </div>
                        </fieldset>
                        <div class="actions-toolbar">
                            <button type="submit" class="action confirm primary" title="<?= $block->escapeHtmlAttr(__('Confirm')) ?>"><span><?= $block->escapeHtml(__('Confirm')) ?></span></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>