<div class="block-content">
	<form class="form form-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="login-form-mobi" data-mage-init='{"validation":{}}'> 
		<?= $block->getBlockHtml('formkey') ?>
		<fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
			<div class="field email required">
				<label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
				<div class="control">
					<input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email_mobi" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
				</div>
			</div>
			<div class="field password required">
				<label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
				<div class="control">
					<input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass_mobi" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
				</div>
			</div>
		   
			<div class="actions-toolbar">
				<div class="primary"><button type="submit" class="action login primary" name="send" id="send2_mobi"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
				<div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Request New Password?')) ?></span></a></div>
				<div class="secondary"><a class="action remind" href="#"><span><?= $block->escapeHtml(__('Create New Password?')) ?></span></a></div>
				<div class="newsletter"><a class="action remind" href="#"><span><?= $block->escapeHtml(__('Newsletter (Sign Up)')) ?></span></a></div>
			</div>
		</fieldset>	
	</form>
</div>

