<?php
$params_url = $block->getRequest()->getParams();
?>
<div class="order-details-items ordered products-grid">
    <?php $_order = $block->getOrder() ?>
	<div class="product-items">
		<div class="order_items product-item">
			<div class="order-h">
				<?php 
					if(isset($params_url['status']) && $params_url['status'] == 'returned'){
						$data_query = $this->helper('Rokanthemes\RokanBase\Helper\Data')->getAmastyRmaRequest($_order->getEntityId());
						if(isset($data_query['created_at'])){
							$order_date = __('Returned on').' '.date("d M Y", strtotime($data_query['created_at']));
						}
						else{
							$order_date = __('Returned on');
						}
					}else{
						if($_order->getStatus() == 'pending'){
							$order_date = __('Placed on').' '.date("d M Y", strtotime($_order->getCreatedAt()));
						}elseif($_order->getStatus() == 'complete'){
							$order_date = __('Esimated Delivered on').' '.date("d M Y", strtotime($_order->getUpdatedAt()));
						}elseif($_order->getStatus() == 'processing'){
							$order_date = __('Delivered on').' '.date("d M Y", strtotime($_order->getUpdatedAt()));
						}else{
							$order_date = date("d M Y", strtotime($_order->getUpdatedAt()));
						}
					}
				?>
				<div class="order-date-update info">
					<div class="date-update">
						<?= $order_date ?> 
					</div> 
					<?php if(isset($params_url['status']) && $params_url['status'] != 'returned'){ ?>
						<div class="review-Improvements">
							<a href="<?= $block->escapeUrl($this->getUrl('reviews/index/index')) ?>"><span><?= $block->escapeHtml(__('Write a review')) ?></span><span><?= $block->escapeHtml(__('Improve this product')) ?></span></a>
						</div>
					<?php }else{ ?>
						<div class="review-Improvements">
							<a href="<?= $block->escapeUrl($this->getUrl('reviews/index/index')) ?>"><span><?= $block->escapeHtml(__('Write a review')) ?></span><span><?= $block->escapeHtml(__('Improve this product')) ?></span></a>
						</div>
					<?php } ?>
				</div>
				<?php if(isset($params_url['status'])){ ?>
					<?php if($params_url['status'] == 'returned'){ ?>
						<div class="order-h-des"><?= $block->escapeHtml(__('Your package was '.$order_date.' . Thank you for shopping at Careshop, We will keep on improving our productand see you on your next purchase!')) ?></div>
					<?php }elseif($params_url['status'] == 'complete'){ ?>
						<div class="order-h-des"><?= $block->escapeHtml(__('Your package '.$order_date.'. Thank you for shopping at Careshop and see you on your next purchase!')) ?></div>
					<?php }else{ ?>
						<div class="order-h-des"><?= $block->escapeHtml(__('Your package has been delivered. Thank you for shopping at Careshop and see you on your next purchase!')) ?></div>
					<?php } ?>
				<?php }else{ ?>
					<div class="order-h-des"><?= $block->escapeHtml(__('Your package has been delivered. Thank you for shopping at Careshop and see you on your next purchase!')) ?></div>
				<?php } ?>
			</div>
			<?= $block->getChildHtml('order_items') ?>
		</div>
	</div>

    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order', $_order)
        && $_order->getGiftMessageId()
    ) : ?>
    <div class="block block-order-details-gift-message">
        <div class="block-title"><strong><?= $block->escapeHtml(__('Gift Message for This Order')) ?></strong></div>
        <?php
        $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($_order);
        ?>
        <div class="block-content">
            <dl class="item-options">
                <dt class="item-sender"><strong class="label"><?= $block->escapeHtml(__('From')) ?></strong><?= $block->escapeHtml($_giftMessage->getSender()) ?></dt>
                <dt class="item-recipient"><strong class="label"><?= $block->escapeHtml(__('To')) ?></strong><?= $block->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                <dd class="item-message">
                    <?= /* @noEscape */
                    $this->helper(\Magento\GiftMessage\Helper\Message::class)->getEscapedGiftMessage($_order) ?>
                </dd>
            </dl>
        </div>
    </div>
    <?php endif; ?>
</div>
