<div id="developer_page">
    <a class="inactive" href="<?= $block->getUrl('community/idea'); ?>"> <button><?= $block->escapeHtml(__('SHARE YOUR IDEAS') ); ?></button></a>
    <a href="<?= $block->getUrl('community/develop-the-product.html'); ?>"class="inactive"><button><?= $block->escapeHtml(__('DEVELOP THE PRODUCT') ); ?></button></a>
    <a href="<?= $block->getUrl('community/test-the-product.html'); ?>" class="inactive"><button><?= $block->escapeHtml(__('TEST THE PRODUCT') ); ?></button></a>
    <a href="<?= $block->getUrl('community/share-your-talent.html'); ?>"><button><?= $block->escapeHtml(__('SHARE YOUR TALENT') ); ?></button></a>
    <p class="idea_title"><?= $block->escapeHtml(__('Careshop belives') ); ?></p>
    <div class="idea_desc">
        <p><?= $block->escapeHtml(__('You are Braven Than You Think, More Talented You Know, and Capable of More Than You Imagine.') ); ?></p>
    </div>
    <p><span><?= $block->escapeHtml(__('Help us to make a great thing even greater. We let you know what we need and you tell us which talent you’d like to share with us.') ); ?></span></p>
    <h4><?= $block->escapeHtml(__('Forum Careshop') ); ?></h4>
    <p><?= $block->escapeHtml(__('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.') ); ?></p>
</div>