<div id="commnuity_page">
    <a href="<?= $block->getUrl('community/idea'); ?>"> <button><?= $block->escapeHtml(__('SHARE YOUR IDEAS') ); ?></button></a> 
    <a href="<?= $block->getUrl('community/develop-the-product.html'); ?>" class="inactive"><button><?= $block->escapeHtml(__('DEVELOP THE PRODUCT') ); ?></button></a>
    <a href="<?= $block->getUrl('community/test-the-product.html'); ?>" class="inactive"><button><?= $block->escapeHtml(__('TEST THE PRODUCT') ); ?></button></a>
    <a href="<?= $block->getUrl('community/share-your-talent.html'); ?>" class="inactive"><button><?= $block->escapeHtml(__('SHARE YOUR TALENT') ); ?></button></a>
    <p class="idea_title"><?= $block->escapeHtml(__('Careshop belives') ); ?> </p>
    <div class="idea_desc">
        <p><?= $block->escapeHtml(__('Describe Your Genius Product Idea and Let the Community') ); ?> </p>
        <p><?= $block->escapeHtml(__('Enhance Your Idea While Conribute to Theirs.') ); ?> </p>
    </div>
    <p><span><?= $block->escapeHtml(__('Our goal í to develop the bét ideas for multifunctional, modular, high quality, fair trade products ever') ); ?> </span></p>
</div> 