<div class="rokan-returnswarranty">
    <div class="rokan-returnswarranty-action">
        <div class="returnswarranty-content">
            <div class="content-h"><h2><?= __('Select products to be returned') ?></h2></div>
            <div class="back"><a href="<?= $block->escapeUrl($this->getUrl('returnswarranty/index/index')) ?>"><?= __('<--- Back to overview') ?></a></div>
            <div class="content-r"><?= __('All products that are eligible for return are displayed here. Please note that you have to return the products to the respec-tive merchant. If you would like to return products from various vendors, you need to send each product seperately. If you have any questions, please consult our ') ?><a href="#"><strong><?= __('Return Policy') ?></strong></a></div>
        </div>
    </div>
</div>