<div class="rokan-returnswarranty">
	<div class="rokan-returnswarranty-action">
		<div class="returnswarranty-content">
			<div class="search-form-orders">
				<div class="field search">
					<div class="control">
						<div class="field">
							<label class="label">
								<span><?php echo __('Order Number') ?> </span>
							</label>
							<div class="control">
								<input id="search-orders" type="text" name="orders_number">
							</div>
						</div>
						<div class="field">
							<label class="label">
								<span><?php echo __('Start Date') ?> </span>
							</label>
							<div class="control">
								<input id="search-startdate" type="date" name="start_date">
							</div>
						</div>
						<div class="field">
							<label class="label">
								<span><?php echo __('End Date') ?> </span>
							</label>
							<div class="control">
								<input id="search-endorders" type="date" name="end_date">
							</div>
						</div>
						<div class="nested">
							<a class="action-returnsorder advanced btn cap">
								<i class="fa fa-search"></i><?php echo __('Search') ?> 
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="list-order-returnsorder">
			</div>
		</div>
	</div>
</div>