<div class="rokan-returnswarranty">
	<div class="rokan-returnswarranty-action">
		<div class="returnswarranty-content">
			<div class="content-h"><h2><?php echo __('What to do in the event of transport damage?') ?><h2></div>
			<div class="content-r transport">
				<div>
					<p><?php echo __('Despite careful packaging and all efforts to deliver flawless products to our customers, transport damage may occur in the minority of cases. Therefore, please always inspect the goods for damages upon delivery. Do not accept damage dgoods, register the issue with the delivery company andinform us of the matter.') ?></p>
					<p><?php echo __('If the above is not possible or the damage is only detected at a later stage, please inform us of the damage within fiv edays (post@careshop.ch).') ?></p>
					<p><?php echo __('To ensure quick handling, the following information and documents will be required:') ?></p>
					<ol>
						<li><?php echo __('Consignment or parcel number') ?></li>
						<li><?php echo __('Description or documentation (photo) of the damage') ?></li>
						<li><?php echo __('Notification regarding how you wish to proceed (return shipment, exchange or credit note)') ?></li>
					</ol>
					<p><?php echo __('Upon receipt of your message, we will inform you of the next steps, depending on where the damage occurred during delivery') ?></p>
					<p><?php echo __('Please do not hesitate to contact our customer service if you have any further questions') ?></p>
				</div>
			</div> 
		</div>
	</div>
</div>