<?php
$brandCollection = $this->getBrandCollection();
$data = $this->helper('Rokanthemes\Brand\Helper\Data');
$show_brand_text = $data->getConfig("product_view_page/show_brand_text");
$brand_text = $data->getConfig("product_view_page/brand_text");
$brand_text = $brand_text?$brand_text:__('Brands: ');
$show_brand_image = $data->getConfig("product_view_page/show_brand_image");
$show_brand_name = $data->getConfig("product_view_page/show_brand_name");
?>
<?php if($brandCollection && $brandCollection->count()){ ?>
	<?php
	$i = 0;
	$total = $brandCollection->count();
	?>
	<?php 
		echo '<div class="container-product-brand-fixed"><ul class="product-brands">';
		foreach ($brandCollection as $_brand) {
			?>
			<li class="brand-item">
				<img src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>"/>
			</li>
			<?php
		}
		echo '</ul></div>';
	?>
<?php } ?>