<div class="block_newsletter">
    <div class='newsletter-title'>
        <h2 class="iner-page"><?= __('Newsletter Sign up'); ?></h2> 
		<h2><?= __('Sign up for newsletter and get CHF 10 off for your first order!'); ?></h2>
        <p><?= /* @escapeNotVerified */ __('Sign up for the CARESHOP newsletter and get more benefits and regular information..') ?></p>     
		<p><?= /* @escapeNotVerified */ __('Get a coupon CHF 10 with new registration') ?></p>		
    </div>
    <div class="content">
        <form class="form subscribe" 
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"  
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?= $block->escapeHtml(__('example@gmail.com')) ?>"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true, 'validate-email':true}"
                    />
                    <button class="action subscribe"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                      <span><?= $block->escapeHtml(__('Subscribe')) ?></span> 
                    </button>
                </div>
            </div>
                
        </form>
    </div>
</div>
