<?php 
    $profile = $block->getProfileByCustommerID();
    $setting = $block->getSettingByCustommerID();
    $tagging = $block->getTaggingByCustomerId();
    $sub_bookmarks = $block->getSubscriptionBookmarks();
    $macros = $block->getMacrosByCustomerId();
    $helper = $block->getHelper();
    $timezones = $helper->getListTimeZone();
    $media_url = $helper->getMediaUrl();
    $default_avatars = $helper->getListDefaultAvatar();
    $list_avatar = $block->getAvatars();
    $email_contents = $helper->getEmailContentOptions();
    $email_formats = $helper->getEmailFormatOptions();
    $board_layout_opts = $helper->getBoardLayoutOptions();
    $display_emoticon_opt = $helper->getEmoticonOptions();
    $rich_editor = $helper->getEditorPostOptions();
    $display_format_date_opt = $helper->getFormatDateOptions();
    $display_show_date_opt = $helper->getFormatDateOptions();
    $display_listview_opt = $helper->getListViewOptions();
    $display_liststyle_opt= $helper->getListStyleOptions();
    $default_flag_topic = $helper->getDefaultFlagTopicsOptions();
    $default_sort_topics = $helper->getDefaultSortTopicsOptions();
    $lenear_sort_topic = $helper->getLenearSortTopicsOptions();
    $lenear_filter_qa = $helper->getLenearTopicFilterOptions();
    $lenear_sort_qa = $helper->getLenearSortQuestionsAnswersOptions();
    $theme_sort_topic = $helper->getThemeSortTopicsOptions();
    $home_private_community = $helper->getPrivateMessagesOptions();
    $home_my_friends = $helper->getMyFriendsMessagesOptions();
    $privacy_person_data = $helper->getPrivacyPersonOptions();
    $privacy_show_email = $helper->getPrivacyShowEmailOptions();
    $privacy_online_status = $helper->getPrivacyShowOnlineOptions();
    $likes_period_rec = $helper->getPeriodLikeReceivedOptions();
    $likes_period_aut = $helper->getPeriodLikeAuthorsOptions();
    $tagging_cloud_filter = $helper->getTaggingCloudOptions();
    $tagging_cloud_age = $helper->getTaggingCloudAgeOptions();
    $all_posts = $helper->getAllPostOptions();
    $mobile_pictures_posts = $helper -> getMobilePicturesInPosts();
   
?>
<div class="change-user-pass">
    <a href="<?= $block->getBaseUrl(); ?>customer/account/edit" class="username"><span><?= $block->escapeHtml(__('Change User Name') ); ?></span></a>
    <a href="<?= $block->getBaseUrl(); ?>customer/account/edit/changepass" class="password"><span><?= $block->escapeHtml(__('Change Password') ); ?></span></a>
</div>
<form class="form subscribe"
    novalidate
    action="#"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="community-customer-form"
    enctype="multipart/form-data" >
    <fieldset class="fieldset">
        <div class="community_customer product data items">
            <?= $block->getChildHtml('community.customer.tab'); ?>
            <div id="tab-macros-opt" class="item content" data-role="content">
                <legend class="label mb-4"><span><?= $block->escapeHtml(__('Macros') ) ?></span></legend>
                <div class="control">
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 1')) ?></span></label>
                        <input 
                            name="title_1" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_1')) ? $block->escapeHtmlAttr( $macros->getData('title_1')) : '' ?>"/>
  
                    </div>
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 2')) ?></span></label>
                        <input 
                            name="title_2" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_2')) ? $block->escapeHtmlAttr( $macros->getData('title_2')) : '' ?>"/>
  
                    </div>
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 3')) ?></span></label>
                        <input 
                            name="title_3" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_3')) ? $block->escapeHtmlAttr( $macros->getData('title_3')) : '' ?>"/>
  
                    </div>
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 4')) ?></span></label>
                        <input 
                            name="title_4" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_4')) ? $block->escapeHtmlAttr( $macros->getData('title_4')) : '' ?>"/>
  
                    </div>
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 5')) ?></span></label>
                        <input 
                            name="title_5" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_5')) ? $block->escapeHtmlAttr( $macros->getData('title_5')) : '' ?>"/>
  
                    </div>
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 6')) ?></span></label>
                        <input 
                            name="title_6" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_6')) ? $block->escapeHtmlAttr( $macros->getData('title_6')) : '' ?>"/>
  
                    </div>
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 7')) ?></span></label>
                        <input 
                            name="title_7" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_7')) ? $block->escapeHtmlAttr( $macros->getData('title_7')) : '' ?>"/>
                    </div>
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 8')) ?></span></label>
                        <input 
                            name="title_8" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_8')) ? $block->escapeHtmlAttr( $macros->getData('title_8')) : '' ?>"/>
                    </div>
                    <div class="field email ">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Title macros 9')) ?></span></label>
                        <input 
                            name="title_9" 
                            class="input-text" 
                            type="text" 
                            value="<?= ($macros->getData('title_9')) ? $block->escapeHtmlAttr( $macros->getData('title_9')) : '' ?>"/>
                    
                    </div>
                </div>
            </div> 
            <!-- End Tab Macros -->
        </div>
    </fieldset>    
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" data-action="update-macros" class="action submit primary" id="community-custom-btn">
                <span><?= $block->escapeHtml(__('Save')); ?></span>
            </button>
        </div>
        <div class="primary">
            <button type="button"  class="action reset primary" id="community-reset-btn">
                <span><?= $block->escapeHtml(__('Reset')); ?></span>
            </button>
        </div>
    </div>
    <div class="msg"></div>

</form>
<div data-mage-init='{"community_customer": {}}'>
    
</div>