<?php 
    $profile = $block->getProfileByCustommerID();
    $setting = $block->getSettingByCustommerID();
    $tagging = $block->getTaggingByCustomerId();
    $sub_bookmarks = $block->getSubscriptionBookmarks();
    $macros = $block->getMacrosByCustomerId();
    $helper = $block->getHelper();
    $timezones = $helper->getListTimeZone();
    $media_url = $helper->getMediaUrl();
    $default_avatars = $helper->getListDefaultAvatar();
    $list_avatar = $block->getAvatars();
    $email_contents = $helper->getEmailContentOptions();
    $email_formats = $helper->getEmailFormatOptions();
    $board_layout_opts = $helper->getBoardLayoutOptions();
    $display_emoticon_opt = $helper->getEmoticonOptions();
    $rich_editor = $helper->getEditorPostOptions();
    $display_format_date_opt = $helper->getFormatDateOptions();
    $display_show_date_opt = $helper->getFormatDateOptions();
    $display_listview_opt = $helper->getListViewOptions();
    $display_liststyle_opt= $helper->getListStyleOptions();
    $default_flag_topic = $helper->getDefaultFlagTopicsOptions();
    $default_sort_topics = $helper->getDefaultSortTopicsOptions();
    $lenear_sort_topic = $helper->getLenearSortTopicsOptions();
    $lenear_filter_qa = $helper->getLenearTopicFilterOptions();
    $lenear_sort_qa = $helper->getLenearSortQuestionsAnswersOptions();
    $theme_sort_topic = $helper->getThemeSortTopicsOptions();
    $home_private_community = $helper->getPrivateMessagesOptions();
    $home_my_friends = $helper->getMyFriendsMessagesOptions();
    $privacy_person_data = $helper->getPrivacyPersonOptions();
    $privacy_show_email = $helper->getPrivacyShowEmailOptions();
    $privacy_online_status = $helper->getPrivacyShowOnlineOptions();
    $likes_period_rec = $helper->getPeriodLikeReceivedOptions();
    $likes_period_aut = $helper->getPeriodLikeAuthorsOptions();
    $tagging_cloud_filter = $helper->getTaggingCloudOptions();
    $tagging_cloud_age = $helper->getTaggingCloudAgeOptions();
    $all_posts = $helper->getAllPostOptions();
    $mobile_pictures_posts = $helper -> getMobilePicturesInPosts();
   
?>
<div class="change-user-pass">
    <a href="<?= $block->getBaseUrl(); ?>customer/account/edit" class="username"><span><?= $block->escapeHtml(__('Change User Name') ); ?></span></a>
    <a href="<?= $block->getBaseUrl(); ?>customer/account/edit/changepass" class="password"><span><?= $block->escapeHtml(__('Change Password') ); ?></span></a>
</div>
<form class="form subscribe"
    novalidate
    action="#"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="community-customer-form"
    enctype="multipart/form-data" >
    <fieldset class="fieldset">
        <div class="community_customer product data items">
            <?= $block->getChildHtml('community.customer.tab'); ?>
            <div id="tab-tagging" class="item content" data-role="content">
                <div class="product data items"
                    data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 0, "disabled": [13], "disabledState": "disabled"}}'>
                    <div class="item title" data-role="collapsible">
                        <a class="switch" data-toggle="trigger" href="#tab-tagging-opt"><?= $block->escapeHtml(__('Tagging Options') ); ?></a>
                    </div>
                    <div id="tab-tagging-opt" class="item content" data-role="content">
                        <legend class="label mb-4"><span><?= $block->escapeHtml(__('Tagging Options') ) ?></span></legend>
                        <div class="control">
                            <div class="field name">
                                <div class="form-group">
                                    <label class="label required-1" for="title"><span><?= $block->escapeHtml(__('Active Tagging')) ?></span></label> 
                                    <input 
                                        name="tagging_active"  
                                        class="input-text" 
                                        type="checkbox" 
                                        <?= ($tagging->getData('tagging_active') && $tagging->getData('tagging_active') == 1) ? 'checked' : '' ?> />
                                </div>  
                            </div>  
                            <div class="field name">
                                <div class="form-group">
                                    <label class="label" for="title"><span><?= $block->escapeHtml(__('Add a seperator beetween tags in clouds')) ?></span></label> 
                                    <input 
                                        name="tagging_seperator"  
                                        class="input-text" 
                                        type="checkbox" 
                                        <?= ($tagging->getData('tagging_seperator') && $tagging->getData('tagging_seperator') == 1) ? 'checked' : '' ?> />
                                </div>
                            </div>
                            <div class="field name">
                                <div class="form-group">
                                    <label class="label" for="title"><span><?= $block->escapeHtml(__('Show number of tags')) ?></span></label> 
                                    <input 
                                        name="tagging_show_num"  
                                        class="input-text" 
                                        type="checkbox" 
                                        <?= ($tagging->getData('tagging_show_num') && $tagging->getData('tagging_show_num') == 1) ? 'checked' : '' ?> />
                                </div>
                            </div>
                            <div class="field name w-65">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Number of tags in the "tag cloud" components')) ?></span></label> 
                                <input 
                                    name="tagging_number"  
                                    class="input-text tagging-number" 
                                    type="text" 
                                    value="<?= ($tagging->getData('tagging_number')) ? $block->escapeHtmlAttr($tagging->getData('tagging_number')) : '' ?>"/>   
                            </div>
                            <div class="field name w-65">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Number of tags in the  components "Top-Tagger"')) ?></span></label> 
                                <input 
                                    name="tagging_number_top"  
                                    class="input-text tagging-number-top" 
                                    type="text" 
                                    value="<?= ($tagging->getData('tagging_number_top')) ? $block->escapeHtmlAttr($tagging->getData('tagging_number_top')) : '' ?>"/>   
                            </div>
                            <div class="field name w-65">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Tag page: Posts per day')) ?></span></label> 
                                <input 
                                    name="tagging_page"  
                                    class="input-text tagging-page" 
                                    type="text" 
                                    value="<?= ($tagging->getData('tagging_page')) ? $block->escapeHtmlAttr($tagging->getData('tagging_page')) : '' ?>"/>   
                            </div>
                            <div class="field name w-65">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Tagging details page: Size tag cloud')) ?></span></label> 
                                <input 
                                    name="tagging_size_cloud"  
                                    class="input-text tagging-size-cloud" 
                                    type="text" 
                                    value="<?= ($tagging->getData('tagging_size_cloud')) ? $block->escapeHtmlAttr($tagging->getData('tagging_size_cloud')) : '' ?>"/>   
                            </div>
                            <div class="field name w-65">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Tagging details page: Posts per group')) ?></span></label> 
                                <input 
                                    name="tagging_per_posts"  
                                    class="input-text tagging-per-posts" 
                                    type="text" 
                                    value="<?= ($tagging->getData('tagging_per_posts')) ? $block->escapeHtmlAttr($tagging->getData('tagging_per_posts')) : '' ?>"/>   
                            </div>
                            <div class="field name w-65">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Tagging details page: Size top tagger list')) ?></span></label> 
                                <input 
                                    name="tagging_size_tagger"  
                                    class="input-text size-tagger" 
                                    type="text" 
                                    value="<?= ($tagging->getData('tagging_size_tagger')) ? $block->escapeHtmlAttr($tagging->getData('tagging_size_tagger')) : '' ?>"/>   
                            </div>
                            <div class="field name w-65">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Size tag clouds in posts')) ?></span></label> 
                                <input 
                                    name="tagging_cloud_posts"  
                                    class="input-text cloud-posts" 
                                    type="text" 
                                    value="<?= ($tagging->getData('tagging_cloud_posts')) ? $block->escapeHtmlAttr($tagging->getData('tagging_cloud_posts')) : '' ?>"/>   
                            </div> 
                            <div class="field name">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Tag cloud content filter')) ?></span></label>
                                <?php 
                                    foreach ($tagging_cloud_filter	 as $value => $label) {
                                ?>
                                        <div class="form-group">
                                            <label class="label" for="title"><span><?= $block->escapeHtml($label) ?></span></label>   
                                            <input 
                                                name="tagging_cloud_filter"  
                                                title="<?= $block->escapeHtmlAttr($label) ?>"  class="input-text"
                                                type="radio"
                                                value="<?= $block->escapeHtmlAttr($value) ?>"
                                                <?= ($tagging->getData('tagging_cloud_filter') && $tagging->getData('tagging_cloud_filter') == $value) ? 'checked' : '' ?> />
                                        </div>        
                                <?php 
                                    }
                                ?>
                            </div>
                            <div class="field name">
                                <label class="label" for="title"><span><?= $block->escapeHtml(__('Show tag cloud content by age')) ?></span></label>
                                <?php 
                                    foreach ($tagging_cloud_age	 as $value => $label) {
                                ?>
                                        <div class="form-group">
                                            <label class="label" for="title"><span><?= $block->escapeHtml($label) ?></span></label>   
                                            <input 
                                                name="tagging_cloud_age"  
                                                title="<?= $block->escapeHtmlAttr($label) ?>"  class="input-text"
                                                type="radio"
                                                value="<?= $block->escapeHtmlAttr($value) ?>"
                                                <?= ($tagging->getData('tagging_cloud_age') && $tagging->getData('tagging_cloud_age') == $value) ? 'checked' : '' ?> />
                                        </div>        
                                <?php 
                                    }
                                ?>
                            </div>                         
                        </div>
                    </div>
                    <!-- End Tab Tagging Options  -->                
                    <div class="item title" data-role="collapsible">
                        <a class="switch" data-toggle="trigger" href="#tab-tags-opt"><?= $block->escapeHtml(__('Tags') ); ?></a>
                    </div>
                    <div id="tab-tags-opt" class="item content" data-role="content">
                        <?= $block->escapeHtml(__('No tags for the ad') ) ?>
                    </div>         
                    <!-- End Tab Tags -->
                </div>
            </div>
            <!-- End Tab Tagging -->
        </div>
    </fieldset>    
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" data-action="update-tagging" class="action submit primary" id="community-custom-btn">
                <span><?= $block->escapeHtml(__('Save')); ?></span>
            </button>
        </div>
        <div class="primary">
            <button type="button"  class="action reset primary" id="community-reset-btn">
                <span><?= $block->escapeHtml(__('Reset')); ?></span>
            </button>
        </div>
    </div>
    <div class="msg"></div>

</form>
<div data-mage-init='{"community_customer": {}}'>
    
</div>