<div class="rokan-rewards">
	<div class="rewards-content">
		<div class="content">
			<div class="circle-icon"><i class="fa fa-users"></i></div>
			<div class="content-title"><h2><?php echo __('Collborate & Earn') ?></h2h2></div>
			<p><?php echo __('Let the community enhance your idea while you contribute to theirs. Each time you invent or contribute, you earn a') ?> <strong><?php echo __('CareshopCoin') ?></strong></p>
		</div>	
		<div class="content">
			<div class="circle-icon"><i class="fa fa-dollar"></i></div>
			<div class="content-title"><h2><?php echo __('Cash In?') ?></h2></div>
			<p><?php echo __('Sorry, no personal earning. But every time a Careshop product sells that you helped to develop - or contributed to - all of us earn and safe money, because of purchasing a high quality, long-lasting, multi-functional and very affordable product. Almost forever.') ?></p>
		</div>	
	</div>
</div>