<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>
<?php 
$storeCode = $this->helper('Rokanthemes\RokanBase\Helper\Data')->getStoreCode();
$add_text = $block->escapeHtml(__('Add to Wishlist'));
if($storeCode == 'de'){
   $add_text = $block->escapeHtml(__('Zur Wunschliste hinzufügen')); 
}
elseif($storeCode == 'it'){
   $add_text = $block->escapeHtml(__('Aggiungi alla lista desideri')); 
}
elseif($storeCode == 'fr'){
   $add_text = $block->escapeHtml(__("Ajouter à la liste d'achats")); 
}
?>
<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist"><span><?= $add_text ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
