<div id="developer_page">
  <a class="inactive" href="<?= $block->getUrl('community/idea'); ?>"> <button><?= $block->escapeHtml(__('SHARE YOUR IDEAS xxxxxxxxx') ); ?></button></a>
  <a href="<?= $block->getUrl('community/product/developer'); ?>" class="active"><button><?= $block->escapeHtml(__('DEVELOP THE PRODUCT') ); ?></button></a>
  <a class="inactive"><button><?= $block->escapeHtml(__('TEST THE PRODUCT') ); ?></button></a>
  <a class="inactive"><button><?= $block->escapeHtml(__('SHARE YOUR TALENT') ); ?></button></a>
  <p class="idea_title"><?= $block->escapeHtml(__('Careshop belives') ); ?> </p>
  <div class="idea_desc">
    <p><?= $block->escapeHtml(__('Careshop Selects Product Ideas from the Community for Development and Manufacturing and Brings Them to Market in No Time') ); ?> </p>
    <p><?= $block->escapeHtml(__('A platform where inovators mêt designers mêt engineers mêt developer meets critical consumer mêt ... YOU!') ); ?> </p>
  </div>
  <h4><?= $block->escapeHtml(__('Forum Careshop') ); ?></h4>
  <p><span><?= $block->escapeHtml(__('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ') ); ?> </span></p>
</div>
<div id="product_developer">
    
</div>
<style>
#developer_page .inactive button{background:#000;}
</style>