<?php

namespace Careshop\CommunityIdea\Model\Config\Backend;

use Magento\Framework\App\Config\Value;
use Magento\Framework\Exception\ValidatorException;

class Pagination extends Value
{
    /**
     * @return Value|void
     * @throws ValidatorException
     */
    public function beforeSave()
    {
        if (!empty($this->getValue())) {
            $valueArray = explode(',', $this->getValue());
            foreach ($valueArray as $value) {
                if (!is_numeric($value) || $value < 1) {
                    throw new ValidatorException(__('Pagination value must be a positive integer.'));
                }
            }
        }
        parent::beforeSave(); // TODO: Change the autogenerated stub
    }
}
