<?php if($block->getConfig('enable') > 0){ ?>
<?php
	$image = '';
	if($block->getConfig('image')){
		$folderName = \Rokanthemes\RokanBase\Model\Config\Newsletterimage::UPLOAD_DIR;
		$path = $folderName . '/' .$block->getConfig('image');
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
		$image = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA).$path;
	}
?>
<div id="newsletter_pop_up" class="newsletterpopup">
	<div class="col-newsletter-popup col-content">
		<div class="content-popup">
			<div class="content">
				<div class="title"><?= __('CARESHOP Newsletter') ?></div>
				<div class="des"><?php echo $block->getConfig('content');?></div>
				<?php if($image){ ?>
					<div class="image"><img src="<?= $image ?>" alt="<?= __('Image Newsletter') ?>"></div>
				<?php } ?>
			</div>
			<form class="form subscribe"
				novalidate
				action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
				method="post"
				data-mage-init='{"validation": {"errorClass": "mage-error"}}'
				id="newsletter-validate-popup">
				<div class="field newsletter">
					<label class="label"><?= $block->escapeHtml(__('Email')) ?></label>
					<div class="control">
						<input name="email" type="email" id="newsletter-popup"
									placeholder="<?php /* @escapeNotVerified */ echo __('example@gmail.com') ?>"
									data-validate="{required:true, 'validate-email':true}"/>
					</div>
				</div>
				<div class="actions">
					<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
						<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
					</button>
				</div>
			</form>	
		</div>
	</div>
</div>
<script> 
require(['jquery','Magento_Ui/js/modal/modal'], function($, modal){
	$(document).ready(function(){
		var options = {
			type: 'popup',
			responsive: true,
			innerScroll: true,
			title: 'Newsletter',
			modalClass: 'newsletter-modal',
			buttons: [{
				text: 'close',
				class: '',
				click: function () {
					this.closeModal();
				}
			}],
			opened: function($event) {
				$(".modal-footer").hide();
			}
		};

		var popup = modal(options, $('#newsletter_pop_up'));
		$(".subscribe-now").on('click',function(){ 
			$("#newsletter_pop_up").modal("openModal");
			return false;
		});
	});
 });	 
</script>
<?php } ?>