<?php 
use Magento\Framework\App\Action\Action;
$_productCollection = $this->getProducts();
$pricingHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
$_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="rokan-newproduct-folk grid products-grid"> 
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_list';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<div class="rokan-product-heading rokan-onsale-heading"><h2><?php echo __('Folks also bought') ?></h2></div>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-newproduct-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<div class="folks-also-bought">
				<?php $_collectionSize = $_productCollection->count() ?>
				<?php $i=0; foreach ($_productCollection as $_product): ?>
				<div class='item newproductslider-item'>

					<div class="product-item">
						<div class="product-item-info ">
							<?php
							$productImage = $block->getImage($_product, $image);
							?>
							<?php // Product Image ?>
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>
							<div class="product details product-item-details">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</strong>
								<div class="original-price-instead-of-common">
							        <?php echo __('Instead of').': '.$pricingHelper->currency($_product->getData('original_price'), true, false); ?>
							    </div>
								<?= /* @noEscape */ $block->getProductPrice($_product) ?> 

							</div>
							<?php $i++;?>
						</div>
					</div>
				</div>
				<?php endforeach; ?>               
			</div>
	<?php endif; ?>
</div>