<?php 
use Magento\Framework\App\Action\Action;
$_productCollection = $this->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$pricingHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
	?>
	<div class="rokan-newproduct-folk grid products-grid">
		<?php
			$viewMode = 'list';
			$image = 'category_page_list';
			$showDescription = true;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$pos = $block->getPositioned();
			
		?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-newproduct-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<div class="rokan-product-heading rokan-onsale-heading"><h2><?php echo __('Folks who viewed this item also viewed') ?></h2></div>
			<div class="who-viewed-this-item-also-viewed owl-carousel owl-theme" data-buttonsplaypause="true" data-rtl="false" data-items="4.5" data-bigdesktop="4.5" data-smalldesktop="4.5" data-bigtablet="3.5" data-tablet="3.5" data-smalltablet="2.5" data-mobile="1.5" data-margin="28" data-loop="true" data-center="false" data-mousedrag="true" data-touchdrag="true" data-stagepadding="1" data-nav="Next" data-navnext="Next" data-navprev="Prev" data-rewind="true" data-dots="false" data-lazyload="false" data-autoplay="false" data-autoplaytimeout="3000" data-autoplayhoverpause="false" data-speed="250">
				<?php $_collectionSize = $_productCollection->count() ?>
				<?php $i=0; foreach ($_productCollection as $_product): ?>
				<div class='item product-items'>

					<div class="product-item">
						<div class="product-item-info ">
							<?php
							$productImage = $block->getImage($_product, $image);
							?>
							<?php // Product Image ?>
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>
							<div class="product details product-item-details">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</strong>
								<?= /* @noEscape */ $block->getProductPrice($_product) ?> 
								<div class="original-price-instead-of-common">
							        <?php echo __('Instead of').': '.$pricingHelper->currency($_product->getData('original_price'), true, false); ?>
							    </div>
								<div class="product-ratting">
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								</div>
							</div>
							<?php $i++;?>
						</div>
					</div>
				</div>
				<?php endforeach; ?>               
			</div>
	<?php endif; ?>
</div>