<div class="block account-nav">
    <div class="title account-nav-title">
        <strong>
            My Account </strong>
    </div>
    <div class="content account-nav-content" id="account-nav">
        <ul class="nav items">
            <li class="nav item current"><strong>My Account</strong></li>
            <li class="nav item"><a href="<?php echo $block->getUrl('notifications/index/index') ?>">Notifications</a>
            </li>
            <li class="nav item"><a href="<?php echo $block->getUrl('sales/order/history') ?>">My Orders</a></li>
            <li class="nav item"><a href="<?php echo $block->getUrl('repair/index/index') ?>">Repair</a></li>
            <li class="nav item"><a href="<?php echo $block->getUrl('returns-and-warranty') ?>">Returns
                    &amp; Warranty</a>
            </li>
            <li class="nav item"><a href="<?php echo $block->getUrl('reviews/index/index') ?>">Reviews
                    / Improvements</a></li>
            <li class="nav item"><a href="<?php echo $block->getUrl('rewards/index/index') ?>">Rewards</a>
            </li>
            <li class="nav item"><a href="<?php echo $block->getUrl('downloadable/customer/products') ?>">My
                    Downloadable
                    Products</a></li>
            <li class="nav item"><a href="<?php echo $block->getUrl('wishlist') ?>">My Wish
                    List</a></li>
            <li class="nav item">
                <span class="delimiter"></span>
            </li>
            <li class="nav item"><a
                    href="<?php echo $block->getUrl('repair/index/index') ?>http://careshop24.com/en/customer/address/">Address
                    Book</a></li>
            <li class="nav item"><a
                    href="<?php echo $block->getUrl('repair/index/index') ?>http://careshop24.com/en/customer/account/edit/">Account
                    Information</a></li>
            <li class="nav item"><a
                    href="<?php echo $block->getUrl('repair/index/index') ?>http://careshop24.com/en/vault/cards/listaction/">Stored
                    Payment Methods</a>
            </li>
            <li class="nav item">
                <span class="delimiter"></span>
            </li>
            <li class="nav item"><a href="<?php echo $block->getUrl('review/customer') ?>">My Product Reviews</a></li>
            <li class="nav item"><a href="<?php echo $block->getUrl('newsletter/manage') ?>">Newsletter
                    Subscriptions</a></li>
            <li class="nav item"><a href="<?php echo $block->getUrl('rma/account/history') ?>">My Returns</a></li>
            <li class="nav item"><a href="<?php echo $block->getUrl('community/customer/profile') ?>">My Comunity
                    Profile</a>
            </li>
            <li class="nav item"><a href="<?php echo $block->getUrl('community/customer/setting') ?>">My Comunity
                    Settings</a>
            </li>
        </ul>
    </div>
</div>