<?php
$_brandCollection = $block->getBrandCollection();
?>
<div class="rokan-widget-brand-widget">
	<ul id="rokan-carousel-brand-home-page" class="owl-carousel owl-theme" data-rtl="false" data-items="6" data-bigdesktop="6" data-smalldesktop="5" data-bigtablet="4" data-tablet="3" data-smalltablet="2" data-mobile="2" data-margin="0" data-loop="true" data-center="true" data-mousedrag="true" data-touchdrag="true" data-stagepadding="1" data-nav="true" data-navnext="<?php echo __('Next');?>" data-navprev="<?php echo __('Prev');?>" data-rewind="true" data-dots="false" data-lazyload="false" data-autoplay="false" data-autoplaytimeout="5000" data-autoplayhoverpause="true" data-speed="250">
		<?php foreach ($_brandCollection as $_brand) { ?>
		<li class="item">
			<div class="brand-image"><img src="<?php echo $_brand->getThumbnailUrl(); ?>" alt="<?php echo $_brand->getName(); ?>"/></div>
		</li>
		<?php } ?>
	</ul>
</div>