<?php
$_item = $block->getItem();
$product = $_item->getProduct();
$productId = $product->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$rokanthemes_brand = $resource->getTableName('rokanthemes_brand');
$rokanthemes_brand_product = $resource->getTableName('rokanthemes_brand_product');

$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item custom-cart-item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                     <?php
                   $query = "SELECT $rokanthemes_brand.brand_id, $rokanthemes_brand.image, $rokanthemes_brand_product.product_id
                    FROM $rokanthemes_brand
                    INNER JOIN $rokanthemes_brand_product ON $rokanthemes_brand.brand_id = $rokanthemes_brand_product.brand_id
                    WHERE $rokanthemes_brand_product.product_id = $productId";

                    $result = $connection->fetchAll($query);
                      $baseUrl = $_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['HTTP_HOST'];
                    foreach ($result as $row) {
                        $image = $row['image'];
                        echo "<img src='$baseUrl/media/$image' alt='Brand Image'>";
                    }

                    ?>
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else :?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">

                        <?php 
                        $totel = '';

                        foreach ($_options as $_option) :?>
                            <?php
                            if (isset($_option['label']) && $_option['label'] === 'Color' && isset($_option['value'])) {
                                    $color = $_option['value'];
                                }
                                if (isset($_option['label']) && $_option['label'] === 'Size' && isset($_option['value'])) {
                                    $size = $_option['value'];
                                }
                                if (isset($color) && isset($size)) {
                                    $totel = $color . ' / ' . $size;
                                }
                            ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option)?>
                            <!-- <dt><?= $block->escapeHtml($_option['label']) ?></dt> -->
                          <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?> 
                                     <?= $block->escapeHtml($totel, ['span', 'a']) ?> 
                                <?php endif; ?>
                            </dd> 
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) :?>
                    <?php foreach ($messages as $message) :?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp) :?>
            <td class="col msrp" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else :?>
            <!-- <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td> -->
        <?php endif; ?>
     <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
        <select name="qty" class="qtyid" data-productid="<?= $block->escapeHtmlAttr($_item->getId()) ?>">
            <?php
            $currentQty = $block->getQty(); 
            for ($i = 1; $i <= 100; $i++) {
                $selected = ($i == $currentQty) ? 'selected' : '';
                echo '<option title="' . $block->escapeHtmlAttr(__('Qty')) . '" value="' . $i . '" ' . $selected . '>' . $i . '</option>';
            }
            ?>
        </select>

            <div class="field qty">
                <div class="control qty">
                    <a class="qty-down-fixed-onclick-page-cart" href="#"><i class="fa fa-minus"></i></a>
					<input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
						   name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
						   data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
						   value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
						   type="text"
						   size="4"
						   step="any"
						   title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
						   class="input-text qty"
						   data-validate="{required:true,'validate-greater-than-zero':true}"
						   data-role="cart-item-qty">
                    <a class="qty-up-fixed-onclick-page-cart" href="#"><i class="fa fa-plus"></i></a>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp) :?>
                <span class="cart msrp subtotal">--</span>
            <?php else :?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
<script type="text/javascript">
require(['jquery'], function($) {
    $(document).on('change', '.qtyid', function() {
        var selectedSubject = $(this).val(); 
        var idAttribute = $(this).data('productid');
        
        setTimeout(function() {
            $('#cart-' + idAttribute + '-qty').val(selectedSubject); 
        }, 100);
        
        setTimeout(function() {
            $('.action.update').trigger('click');
        }, 200);
    });
});
</script>


