<div id="developer_page"> 
    <a class="inactive" href="<?= $block->getUrl('community/idea'); ?>"> <button><?= $block->escapeHtml(__('SHARE YOUR IDEAS') ); ?></button></a>
    <a href="<?= $block->getUrl('community/develop-the-product.html'); ?>"><button><?= $block->escapeHtml(__('DEVELOP THE PRODUCT') ); ?></button></a>
    <a href="<?= $block->getUrl('community/test-the-product.html'); ?>" class="inactive"><button><?= $block->escapeHtml(__('TEST THE PRODUCT') ); ?></button></a>
    <a href="<?= $block->getUrl('community/share-your-talent.html'); ?>" class="inactive"><button><?= $block->escapeHtml(__('SHARE YOUR TALENT') ); ?></button></a>
    <p class="idea_title"><?= $block->escapeHtml(__('Careshop belives') ); ?></p>
    <div class="idea_desc">
        <p><?= $block->escapeHtml(__('Careshop Selects Product Ideas from the Community for Development and Manufacturing and Brings Them to Market in No Time') ); ?></p>
        <p><?= $block->escapeHtml(__('A platform where inovators mêt designers mêt engineers mêt developer meets critical consumer mêt ... YOU!') ); ?></p>
    </div>
    <h4><?= $block->escapeHtml(__('Forum Careshop') ); ?></h4>
    <p><?= $block->escapeHtml(__('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation') ); ?></p>
</div>