<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="container-breadcrumbs-fixed">
        <div class="breadcrumbs">
            <div class="container">
                <ul class="items">
                    <li class="item home">
                        <a href="<?= $block->getUrl('community'); ?>" title="<?= $block->escapeHtml(__('Community Overview')); ?>"><?= $block->escapeHtml(__('Community Overview')); ?></a>
                    </li>
                    <li class="item category16"> <?= $block->escapeHtml(__('Talent The Product')); ?></li> 
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
