<?php  
    $develop = $block->getDevelop();
    $product = $block->getProduct();
    $customer_id = $develop->getCustomerId();
    $customer = $block->getAuthorByCustomerId($customer_id);
    $media_url = $block->getMediaUrl();
    if( $customer_id > 0 ) {
        $profile = $block->getCustomerProfile($customer_id);
        $avatar = $media_url.$profile->getAvatar();
    }
?>
<form class="form"  id="form_reply_idea"
    novalidate
    action="#"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    enctype="multipart/form-data" 
    data-mage-init='{"validation":{}}'> 
    <div class="control">
        <div class="field">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Send message')) ?></span></label>
            <div class="control">
                <div class="field field-name required">
                    <input name="name" type="text" id="name" placeholder="<?= $block->escapeHtmlAttr(__('Message name')) ?>" data-validate="{required:true}">
                </div>
                <textarea 
                    id="content_message"
                    name="message" 
                    title="<?= $block->escapeHtmlAttr(__('Send message')) ?>" 
                    class="input-text" type="text" 
                    data-validate="{required:true}">
                </textarea>   
                <input name="image" type="file" id="upload" style="visibility:hidden;">
            </div>
        </div>
        <div class="submit">
            <button id="submit_form"><?= $block->escapeHtml(__('Submit') ); ?></button>
        </div>
    </div>
</form>          
<div id="answer_to">
    <h4> <?= $block->escapeHtmlAttr(__('Answer To:')) ?></h4>
    <div class="left">
        <div class="author">
            <b> <?= $block->escapeHtmlAttr(__('Author:')) ?></b>
            <div><span><?= ($customer->getName()) ? $customer->getName(): '' ?></span></div>
            <div><img src="<?= $block->escapeHtmlAttr($avatar) ?>" alt="<?= $develop->getName() ?>" /></div>
            <div id="output"></div>
        </div>   
        </div>
    </div>
    <div class="right">
        <div class="idea_name"><span><?= ($develop->getName()) ? $develop->getName(): '' ?></span></div>
        <div class="idea_by"><?= $block->escapeHtml(__('By: ')) ?><span class="idea_name"><?= ($customer->getName()) ? $customer->getName(): '' ?></span>-<span><?= ($develop->getCreatedAt()) ? $block->getDateFormat($develop->getCreatedAt()) : '' ?></span></div>
        <div class="product"><?= $block->escapeHtml(__('Develop The Product: ')) ?><a href="<?= $product->getProductUrl() ?>" class="product_name"><?= ($product->getName()) ? $product->getName(): '' ?></a></div>
    </div>
</div>    
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
    var dataForm = $('#form_reply_idea');
    dataForm.mage('validation', {});
    $('#submit_form').click(function(){
        dataForm.sumbmit();
    });
});
</script>
<script type="text/javascript">
require([
        'jquery',
        "mage/url",
        'mage/adminhtml/wysiwyg/tiny_mce/setup'
    ], function($,urlBuilder){
        tinymce.init({
            selector: "#content_message",
            theme: "modern",
            paste_data_images: true,
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            menubar: false,
            image_advtab: true,
            file_picker_callback: function(callback, value, meta) {
                if (meta.filetype == 'image') {
                    $('#upload').trigger('click');
                    $('#upload').on('change', function() {
                        var file = this.files[0];
                    
                        var reader = new FileReader();
                        reader.onload = function(e) {
                            console.log(e.target.result);
                        callback(e.target.result, {
                        alt: ''
                    });
                    };
                    reader.readAsDataURL(file);
                    });
                }
            }
        });

});
</script> 
<style>
.left {width:30%; float:left; margin-top:30px;}
.right{width:70%; float:right; margin-top:30px;}
.field-name{width:100%; margin-bottom:30px;}
.field-name input{width:100%}
.idea_name { font-weight:bold;}
.page-title-wrapper { display:none;}
.report{color:#f05735;}
</style>