<div id="developer_page">
    <a class="inactive" href="<?= $block->getUrl('community/idea'); ?>"> <button><?= $block->escapeHtml(__('SHARE YOUR IDEAS') ); ?></button></a>
    <a href="<?= $block->getUrl('community/develop-the-product.html'); ?>"class="inactive"><button><?= $block->escapeHtml(__('DEVELOP THE PRODUCT') ); ?></button></a>
    <a href="<?= $block->getUrl('community/test-the-product.html'); ?>" ><button><?= $block->escapeHtml(__('TEST THE PRODUCT') ); ?></button></a>
    <a href="<?= $block->getUrl('community/share-your-talent.html'); ?>" class="inactive"><button><?= $block->escapeHtml(__('SHARE YOUR TALENT') ); ?></button></a>
    <p class="idea_title"><?= $block->escapeHtml(__('Careshop belives') ); ?></p>
    <div class="idea_desc">
        <p><?= $block->escapeHtml(__('Testers Don’t like to Break Things: They like to Dispel the Illustion That Things Work.') ); ?></p>
    </div>
    <p><span><?= $block->escapeHtml(__('Buy and test the developed product for a fraction of the retail price, in return test and rate the product. Easy peasy.') ); ?><span></p>
    <h4><?= $block->escapeHtml(__('Forum Careshop') ); ?></h4>
    <p><?= $block->escapeHtml(__('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.') ); ?></p>
</div>